FROM registry.fedoraproject.org/fedora:31

RUN dnf -y update && \
    dnf -y install --setopt=tsflags=nodocs --setopt=install_weak_deps=false \
      ansible \
      openssh-server \
      sudo && \
	dnf clean all && \
	rm -rf /var/cache/dnf && \
	systemctl enable sshd

RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' /etc/sudoers && \
    mkdir -p /etc/ansible && \
	printf '[local]\nlocalhost ansible_connection=local\n' > /etc/ansible/hosts

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
